[tool.mypy]
python_version = "3.12"
disallow_untyped_defs = true
disallow_any_unimported = true
disallow_incomplete_defs = true
strict_equality = true
warn_redundant_casts = true
warn_unused_ignores = true
pretty = true
show_error_codes = true
